// Catalog sync: after a marketplace pack sync drops new agents/skills into
// .claude/, gate.mjs goes red with "no catalog entry" lines. This tool turns
// that red list into docs/ai/SKILLS.md entries generated from each item's
// frontmatter description. Idempotent: green gate = no-op, exit 0.
//
//   node tools/catalog-sync.mjs          # append missing entries, print them
//   node tools/catalog-sync.mjs --check  # self-check (no files touched)
//
// Entries land under the "Marketplace agents/skills" sections (created if
// absent). Those sections are auto-generated; hand-edits there get appended
// around, not preserved in order.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { strict as assert } from "node:assert";

const SKILLS_MD = "docs/ai/SKILLS.md";
const AGENT_HEADER = "## Marketplace agents (.claude/agents/, synced pack)";
const SKILL_HEADER = "## Marketplace skills (.claude/skills/, synced pack)";
const GEN_NOTE =
  "Auto-generated by tools/catalog-sync.mjs from frontmatter; rerun on pack sync.";

export function parseMissing(gateOutput) {
  return [...gateOutput.matchAll(/no catalog entry for (agent|skill) (\S+)/g)]
    .map((m) => ({ kind: m[1], name: m[2] }));
}

export function extractDescription(fileText) {
  const fm = fileText.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!fm) return null;
  const m = fm[1].match(/^description:\s*(?:[>|][-+]?\s*)?([\s\S]*?)(?=\r?\n\S|$)/m);
  if (!m) return null;
  let d = m[1].replace(/\s+/g, " ").trim().replace(/^["']|["']$/g, "");
  const dot = d.indexOf(". ");
  if (dot > 20) d = d.slice(0, dot);
  if (d.length > 100) d = d.slice(0, 97).replace(/\s+\S*$/, "") + "...";
  return d || null;
}

function entryFor({ kind, name }) {
  const file =
    kind === "agent"
      ? `.claude/agents/${name}.md`
      : `.claude/skills/${name}/SKILL.md`;
  const d =
    (existsSync(file) && extractDescription(readFileSync(file, "utf8"))) ||
    "(no description in frontmatter)";
  return `- ${name} — ${d}`;
}

// Append entries under a section header, creating the section at EOF if new.
export function appendToSection(doc, header, entries) {
  if (!entries.length) return doc;
  const block = entries.join("\n");
  const idx = doc.indexOf(header);
  if (idx === -1)
    return `${doc.trimEnd()}\n\n${header}\n\n${GEN_NOTE}\n\n${block}\n`;
  // Insert at the end of the existing section (before the next "## " or EOF).
  const next = doc.indexOf("\n## ", idx + header.length);
  const end = next === -1 ? doc.length : next;
  return doc.slice(0, end).trimEnd() + "\n" + block + "\n" + doc.slice(end);
}

function selfCheck() {
  assert.deepEqual(
    parseMissing(
      "GATE RED:\n - x has no catalog entry for agent foo\n - x has no catalog entry for skill bar-baz\n"
    ),
    [{ kind: "agent", name: "foo" }, { kind: "skill", name: "bar-baz" }]
  );
  assert.equal(parseMissing("gate: OK").length, 0);
  assert.equal(
    extractDescription('---\ndescription: >-\n  Does a thing with many words here. Second sentence.\n---\nbody'),
    "Does a thing with many words here"
  );
  // First sentence under 21 chars stays whole (guard against e.g./vs. cuts).
  assert.equal(
    extractDescription("---\ndescription: Short one. More.\n---\n"),
    "Short one. More."
  );
  assert.equal(extractDescription("no frontmatter"), null);
  const grown = appendToSection("# Doc\n\n## Other\n\n- a\n", SKILL_HEADER, ["- new — d"]);
  assert.ok(grown.includes(SKILL_HEADER) && grown.trimEnd().endsWith("- new — d"));
  const inPlace = appendToSection(
    `# Doc\n\n${SKILL_HEADER}\n\n${GEN_NOTE}\n\n- old — d\n\n## After\n\ntext\n`,
    SKILL_HEADER,
    ["- new — d"]
  );
  assert.ok(inPlace.indexOf("- new — d") > inPlace.indexOf("- old — d"));
  assert.ok(inPlace.indexOf("- new — d") < inPlace.indexOf("## After"));
  console.log("catalog-sync self-check: OK");
}

function main() {
  let gateOut = "";
  try {
    gateOut = execFileSync("node", ["tools/gate.mjs"], { encoding: "utf8" });
  } catch (e) {
    gateOut = `${e.stdout ?? ""}${e.stderr ?? ""}`;
  }
  const missing = parseMissing(gateOut);
  if (!missing.length) {
    console.log("catalog-sync: gate green, nothing to catalog");
    return;
  }
  let doc = readFileSync(SKILLS_MD, "utf8");
  const agents = missing.filter((m) => m.kind === "agent").map(entryFor).sort();
  const skills = missing.filter((m) => m.kind === "skill").map(entryFor).sort();
  doc = appendToSection(doc, AGENT_HEADER, agents);
  doc = appendToSection(doc, SKILL_HEADER, skills);
  writeFileSync(SKILLS_MD, doc);
  console.log([...agents, ...skills].join("\n"));
  console.log(`catalog-sync: added ${agents.length} agents, ${skills.length} skills to ${SKILLS_MD}`);
  // Fail loudly if the gate still complains (e.g. a dir with no SKILL.md —
  // that needs a human, not a catalog line).
  execFileSync("node", ["tools/gate.mjs"], { encoding: "utf8", stdio: "inherit" });
}

process.argv.includes("--check") ? selfCheck() : main();
